name: Continuous Integration

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    branches:
      - "**"

  pull_request:
    branches:
      - "**:**"

  release:

jobs:
  format:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: crystal-lang/install-crystal@v1
      - run: crystal tool format --check

  test:
    runs-on: ubuntu-24.04

    permissions:
      checks: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - uses: crystal-lang/install-crystal@v1

      - run: shards install
      - run: make spec OPTS="-j result.xml"

      - uses: EnricoMi/publish-unit-test-result-action@v2
        if: (!cancelled())
        with:
          files: |
            result.xml
          ignore_runs: true


